version: "3.3"

services:
  nginx:
    build:
      context: ./deploy/nginx
      dockerfile: local.Dockerfile
    ports:
      - "8000:80"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    restart: "on-failure"

  backend:
    volumes:
      - ./backend:/usr/src/app # map data and files from parent directory in host to directory in docker container
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    command: poetry run make run-local
    restart: always

  socketio:
    command: poetry run make socketio-local
